# Jacobi method

In [28]:
# Jacobi method to solve matrix 
import numpy as np
def swap(A):
    A[1],A[2] = A[2],A[1]
    return A
def jacobi(a,b):
    n = len(a)
    D = np.diag(a)
    R = a - np.diagflat(D)
    x = np.zeros(n)
    for i in range(100):
        x = (b - np.dot(R,x)) / D
        print(x)
    return x
A = [
    [4,-1,1],
    [-2,1,5],
    [4,8,4]
]
b = [7,15,-21]
# print (len(A))
jacobi(swap(A),b)

[ 1.75   1.875 -4.2  ]
[ 3.26875  3.1     -3.875  ]
[ 3.49375   2.178125 -3.5125  ]
[ 3.17265625  1.884375   -3.238125  ]
[ 3.030625    1.90773437 -3.3078125 ]
[ 3.05388672  2.01359375 -3.36929687]
[ 3.09572266  2.03270508 -3.38116406]
[ 3.10346729  2.0177207  -3.36825195]
[ 3.09649316  2.00739233 -3.36215723]
[ 3.09238739  2.00783203 -3.3628812 ]
[ 3.09267831  2.01024691 -3.36461145]
[ 3.09371459  2.01096657 -3.36497806]
[ 3.09398616  2.01063173 -3.36470748]
[ 3.0938348   2.01036066 -3.36453188]
[ 3.09372314  2.01034854 -3.36453821]
[ 3.09372169  2.01040754 -3.36458045]
[ 3.093747    2.01042938 -3.36459283]
[ 3.09375555  2.01042292 -3.36458708]
[ 3.0937525   2.01041576 -3.36458236]
[ 3.09374953  2.01041493 -3.36458215]
[ 3.09374927  2.01041631 -3.36458317]
[ 3.09374987  2.01041695 -3.36458355]
[ 3.09375013  2.01041684 -3.36458344]
[ 3.09375007  2.01041666 -3.36458332]
[ 3.09374999  2.01041662 -3.3645833 ]
[ 3.09374998  2.01041665 -3.36458333]
[ 3.09375     2.01041667 -3.36458334]
[ 3.

array([ 3.09375   ,  2.01041667, -3.36458333])

In [31]:
# Jacobi method to solve matrix equation
A = [
    [4,-1,1],
    [-2,1,5],
    [4,8,4]
]
b = [7,15,-21]
def swap(A):
    A[1],A[2] = A[2],A[1]
    return A
#swap(A)
x = 0
y = 0
z = 0
for i in range(10):
    x = (b[0] - A[0][1]*y - A[0][2]*z) / A[0][0]
    y = (b[1] - A[1][0]*x - A[1][2]*z) / A[1][1]
    z = (b[2] - A[2][0]*x - A[2][1]*y) / A[2][2]
    print(x,y,z)
    
    



1.75 18.5 -44.0
17.375 269.75 -562.125
209.71875 3245.0625 -6705.09375
2489.2890625 38519.046875 -79532.6328125
29514.669921875 456707.50390625 -942934.927734375
349912.35791015625 5414514.3544921875 -11178946.316894531
4148366.9178466797 64191480.420166016 -132531333.00817871
49180705.10708618 761018090.2550659 -1571216890.867218
583058747.030571 9022201963.397232 -18627462679.075035
6912416162.368067 106962145735.11131 -220836707637.8407


In [42]:
import math
def Jacobi(A,B):
    n = len(A)
    C = [[1] for y in range(n)]
    D = [[0] for y in range(n)]
    m = 2000
    sum = 0
    e = 0.001
    y = 1
    
    for k in range(m):
     for i in range(n):
        for j in range(n):
            if j!=i:
             sum=sum+A[i][j]*C[j][0]
            
            if abs(D[j][0]-C[j][0]) > e:y=1
                
        if y==1:    
         D[i][0]=(B[i][0]-sum)/A[i][i]
        else:
            
         print(k)
         for line in C:
          print ('  '.join(map(str, line)))
         return C
     
        sum=0
        
     y=0    
     
     C,D=D,C
     

    for line in C:
      print ('  '.join(map(str, line) ))
'''def swap(A):
    A[1],A[2] = A[2],A[1]
    return A'''
A = [
    [4,-1,1],
    [4,-8,1],
    [-2,1,5],
]
B = [[7],[-21],[15]]
Jacobi(A,B)

8
1.9996660156250001
3.9998593749999998
3.0000703125


[[1.9996660156250001], [3.9998593749999998], [3.0000703125]]