# Roots of non linear equations

# 1. Lagurre's method

In [21]:
# deflation
import numpy as np
def f(x):
    return x**4 - x**3 - 7*x**2 + x + 5
def def1(poly0,b0):
    poly1 = np.zeros(len(poly0))
    poly1[0] = poly0[0]
    for i in range(len(poly0)-1):
        poly1[i+1] = poly1[i]*b0 + poly0[i+1]
    return poly1
print(def1([1,-1,-7,1,6],3))
# differentiation
def diff(poly0):
    poly1 = np.zeros(len(poly0)-1)
    n = len(poly0)-1
    for i in range(len(poly0)-1):
        poly1[i] = poly0[i]*(n-i)
    return poly1
print(diff([1,-1,-7,1,6]))
# double differentiation
def diff_1(poly1):
    poly_2 = np.zeros(len(poly1)-1)
    n = len(poly1)-1
    for i in range(len(poly1)-1):
        poly_2[i] = poly1[i]*(n-i)
    return poly_2
print(diff([ 4,  -3, -14,   1]))
# triple differentiation
def diff_1(poly2):
    poly_3 = np.zeros(len(poly2)-1)
    n = len(poly2)-1
    for i in range(len(poly2)-1):
        poly_3[i] = poly2[i]*(n-i)
    return poly_3
print(diff([ 12,  -6, -14]))

[ 1.  2. -1. -2.  0.]
[  4.  -3. -14.   1.]
[ 12.  -6. -14.]
[24. -6.]


[24. -6.]
